cors:
  allowed-clients:
    - "*"

spring:
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    generate-ddl: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wiki?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/wiki?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show-sql: false
    hibernate:
      ddl-auto: validate
server:
  port: 9090
